### PR TITLE
Build against alpha4

### PR DESCRIPTION
**Pull request by jgoldfar**
Looks like this will need to be rebased... The controlgallery example works though, and I went ahead and updated the appveyor configuration; would be nice to turn that on as well.

### CODE REVIEW

**Comment by jgoldfar** [comment]
By the way, I have a branch with some tests that actually use the library (including running the control gallery script) and they pass on Travis AFAIK. Would probably be good to test that you can do more than just load the library... Let me know if you'd accept a PR

**Comment by jgoldfar** [comment]
Ok. Looks like using the tarballs provided by the original GitHub page is problematic... You've probably realized that. Would be good to switch to [BinaryBuilder](https://github.com/JuliaPackaging/BinaryBuilder.jl) if possible; it's a new and fun way to cross-compile libraries for multiple platforms and use GitHub as a host. But, this PR should be ready to go.

**Comment by joa-quim** [comment]
Thanks for this, and yes tests that actually use the library are well come. The controlgallery.jl example stop working for me. The line ``const progressbar = uiNewProgressBar()`` crashes Julia apparently because its trying to create a child window before the main thing. The solution seems to be to get rid of those globals.

**Comment by jgoldfar** [comment]
Indeed; I’ll rebase my branch with the GUI test enabled. I refactored that example to eliminate global variables on that branch as well

**Pull request merged**
